# Generated by Django 5.0.3 on 2024-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memory', models.CharField(choices=[('2GB', 'T Gb'), ('4GB', 'F Gb'), ('8GB', 'S Gb'), ('16GB', 'E Gb'), ('32GB', 'T2 Gb'), ('64GB', 'T3 Gb')], max_length=10)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('manufacturer', models.CharField(choices=[('MSI', 'Msi'), ('GIGABYTE', 'Gigabyte'), ('INTEL', 'Intel'), ('NVIDIA', 'Nvidia'), ('AMD', 'Amd')], max_length=100)),
            ],
        ),
    ]
